{
 "title": "Restarts Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "oneMinute", "query": "now() - 1m" }
  ]
 },
 "panels": [
  {
   "title": "Restarts by Container",
   "type": "table",
   "description": "The number of restarts for each individual container.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "container" ], "type": "tag" }
     ],
     "measurement": "kube_pod_container_status_restarts_total",
     "query": "SELECT \"counter\" FROM \"kube_pod_container_status_restarts_total\" WHERE $timeFilter GROUP BY \"container\"",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Termination Reasons",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"gauge\") FROM \"kube_pod_container_status_terminated_reason\" WHERE (time >= now() - 10s) GROUP BY \"reason\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wait Reasons",
   "type": "table",
   "description": "The reason that containers are waiting.",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "reason" ], "type": "tag" },
      { "params": [ "container" ], "type": "tag" }
     ],
     "measurement": "kube_pod_container_status_waiting_reason",
     "query": "SELECT sum(\"gauge\") FROM \"kube_pod_container_status_waiting_reason\" WHERE (time >= now() - 10s) GROUP BY \"reason\"",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "phase" ], "type": "tag" }
     ],
     "measurement": "kube_pod_status_phase",
     "query": "SELECT (\"gauge\") FROM \"kube_pod_status_phase\" WHERE (\"gauge\" != 0) AND $timeFilter GROUP BY \"pod\", \"phase\"",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "gauge", "operator": "!=", "value": "0" }
     ]
    }
   ]
  }
 ]
}