{
 "title": "Application metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Average OK Response Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf/autogen\")\n  |> range($range)\n  |> filter(fn: (r) => \n     r._measurement == \"nginx_ingress_controller_response_duration_seconds\" and\n     r.ingress == \"example-ingress\" and\n     r.status == \"200\" and\n     r._field == \"sum\"\n     )\n  |> keep(columns: [\"_time\",\"_field\",\"_value\"])\n  |> mean(columns: [\"_value\"])\n  |> limit(n:100)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "graph",
   "description": "Grouped by a 1 minute resolution",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "windows = from(bucket: \"telegraf/autogen\")\n |> range($range)\n |> filter(fn: (r) =>   r._measurement == \"nginx_ingress_controller_requests\" and r.ingress == \"example-ingress\")\n |> group(columns: [\"status\"])\n |> keep(columns: [\"status\", \"_value\", \"_time\"])\n |> window(every: 1m)\n \nfirst = windows\n |> first()\n \nlast = windows\n |> last()\n \n \njoin(tables: {first: first, last: last}, on: [\"_start\", \"_stop\", \"status\"]) \n |> map(fn: (r) => ({\n    _time: r._time_last,\n    _value: r._value_last - r._value_first\n }))\n |> window(every: inf)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests by status code",
   "type": "graph",
   "description": "Requests by status code since last reboot of the Ingress controller",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"telegraf/autogen\") \n|> range($range)\n|> filter(fn: (r) =>   r._measurement == \"nginx_ingress_controller_requests\" and r.ingress == \"example-ingress\")\n|> group(columns: [\"status\"])\n|> keep(columns: [\"status\", \"_value\", \"_time\"])\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}