kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: tick
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: tick
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io